// https://developer.yle.fi/en/api/index.html
// color codes to tailwind classes
export const fgColor = {
  black: "text-black",
  red: "text-red-500",
  green: "text-green-500",
  yellow: "text-yellow-500",
  blue: "text-blue-500",
  magenta: "text-purple-500",
  cyan: "text-indigo-500",
  white: "text-white",
  gblack: "text-black",
  gred: "text-red-500",
  ggreen: "text-green-500",
  gyellow: "text-yellow-500",
  gblue: "text-blue-500",
  gmagenta: "text-purple-500",
  gcyan: "text-indigo-500",
  gwhite: "text-white",
};
export const bgColor = {
  black: "bg-black",
  red: "bg-red-500",
  green: "bg-green-500",
  yellow: "bg-yellow-500",
  blue: "bg-blue-500",
  magenta: "bg-purple-500",
  cyan: "bg-indigo-500",
  white: "bg-white",
  gblack: "bg-black",
  gred: "bg-red-500",
  ggreen: "bg-green-500",
  gyellow: "bg-yellow-500",
  gblue: "bg-blue-500",
  gmagenta: "bg-purple-500",
  gcyan: "bg-indigo-500",
  gwhite: "bg-white",
};
